name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels: "feat"

  - title: "Bug Fixes"
    labels: "fix"

  - title: "Maintenance"
    label: "chore"

  - title: "Documentation"
    label: "docs"

  - title: "Continuos Integration"
    label: "ci"

  - title: "Build"
    label: "build"

  - title: "Performance"
    label: "perf"

  - title: "Refactor"
    label: "refactor"

  - title: "Style"
    label: "style"

  - title: "Test"
    label: "test"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: "major"

  minor:
    labels: "minor"

  patch:
    labels: "patch"

  default: patch

exclude-labels:
  - "skip-changelog"

exclude-contributors:
  - "github-actions[bot]"
  - "dependabot[bot]"

template: |
  ## New in $REPOSITORY v$RESOLVED_VERSION

  $CHANGES
  $CONTRIBUTORS
