name: Bug
description: Report a bug encountered while operating this project
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: ticket
    attributes:
      label: Link to existing issue
      description: If there is an existing issue, please link to it here.
      placeholder: JIRA-123
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: URL
      description: What URL were you on when you encountered the bug?
      placeholder: https://example.com
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - 20.x
        - 18.x
        - 16.x
        - 14.x
        - 12.x
        - 10.x
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Internet Explorer
        - label: Opera
        - label: Brave
        - label: Other
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: operating-system-version
    attributes:
      label: Operating System Version
      description: What version of the operating system are you using?
      placeholder: IOS 14.5.1, Windows 10, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! We'll use the information you've provided to investigate and address the problem.
