name: Bug
description: Report a bug encountered while operating this project
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - label: 18.x
          value: 18.x
        - label: 16.x
          value: 16.x
        - label: 14.x
          value: 14.x
        - label: 12.x
          value: 12.x
        - label: 10.x
          value: 10.x
        - label: Other
          value: other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - label: Chrome
          value: chrome
        - label: Firefox
          value: firefox
        - label: Safari
          value: safari
        - label: Edge
          value: edge
        - label: Other
          value: other
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - label: Windows
          value: windows
        - label: macOS
          value: macos
        - label: Linux
          value: linux
        - label: Android
          value: android
        - label: iOS
          value: ios
        - label: Other
          value: other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
