name: Build

on:
  workflow_call:
    inputs:
      name:
        description: Enter a name for the job
        type: string
        required: false
        default: Build

      runs-on:
        description: use runs-on to define the type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest

      timeout-minutes:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      dockerfile:
        description: Enter the name of the docker file
        type: string
        required: false
        default: Dockerfile

    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  build:
    name: ${{inputs.name}}
    runs-on: ${{inputs.runs-on}}
    timeout-minutes: ${{inputs.timeout-minutes}}
    env:
      REPOSITORY_SLUG: ${{github.event.repository.name}}
      IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/${{github.event.repository.name}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{inputs.dockerfile}}
          tags: ${{env.IMAGE_NAME}}:latest
          outputs: type=docker,dest=/tmp/${{env.REPOSITORY_SLUG}}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.REPOSITORY_SLUG}}
          path: /tmp/${{env.REPOSITORY_SLUG}}.tar
