name: Build

on:
  workflow_call:
    inputs:
      NAME:
        description: Enter a name for the job
        type: string
        required: false
        default: Build

      RUNS_ON:
        description: use runs-on to define the type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest

      TIMEOUT_MINUTES:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      DOCKERFILE:
        description: Enter the name of the docker file
        type: string
        required: false
        default: Dockerfile

    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  build:
    name: ${{ inputs.NAME }}
    runs-on: ${{ inputs.RUNS_ON }}
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      REPOSITORY_SLUG: ${{ github.event.repository.name }}
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.DOCKERFILE }}
          tags: ${{ env.IMAGE_NAME }}:latest
          outputs: type=docker,dest=/tmp/${{ env.REPOSITORY_SLUG }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPOSITORY_SLUG }}
          path: /tmp/${{ env.REPOSITORY_SLUG }}.tar