name: Deploy

on:
  workflow_call:
    inputs:
      name:
        description: Enter a name for the job
        type: string
        required: false
        default: Deploy

      runs-on:
        description: Use runs-on to define the type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest

      timeout-minutes:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      environment:
        description:
        type: string
        required: false
        default: staging

      deploy-command:
        description: Enter the command to run the deploy
        type: string
        required: true

jobs:
  deploy:
    name: ${{inputs.name}}
    runs-on: ${{inputs.runs-on}}
    timeout-minutes: ${{inputs.timeout-minutes}}
    environment: ${{inputs.environment}}
    env:
      REPOSITORY_DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{env.REPOSITORY_SLUG}}
          path: /tmp

      - name: Load Image
        run: docker load --input /tmp/${{env.REPOSITORY_SLUG}}.tar

      - name: Run Test Command
        run: docker run ${{secrets.DOCKERHUB_USERNAME}}/${{env.REPOSITORY_SLUG}}:latest ${{inputs.deploy-command}}
