name: Maintainer

on:
  workflow_call:
    inputs:
      name:
        description: Enter a name for the job
        type: string
        required: false
        default: Maintainer

      runs-on:
        description: use runs-on to define the type of machine to run the job on
        type: string
        required: false
        default: ubuntu-latest

      timeout-minutes:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      image-name:
        description: Enter the name of the image
        type: string
        required: true

    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  maintainer:
    name: ${{inputs.name}}
    runs-on: ${{inputs.runs-on}}
    timeout-minutes: ${{inputs.timeout-minutes}}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: GitHub Repository Metadata
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          ref: ${{env.REPOSITORY_DEFAULT_BRANCH}}

      - name: Synchronize Labels
        uses: julb/action-manage-label@v1
        with:
          from: https://raw.githubusercontent.com/luisfalconmx/.github/main/.github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Dynamic template render
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: luisfalconmx/luisfalconmx
          files: README.md
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          commit_message: 'docs: update readme file [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ env.REPOSITORY_HOMEPAGE_URL }}
          destination: screenshot.png

      - name: Download Screenshot Artifact
        uses: actions/download-artifact@v2
        with:
          name: screenshot
          path: .github/

      - name: Commit Screenshot
        uses: EndBug/add-and-commit@v8
        with:
          add: .github/screenshot.png
          message: 'docs: screenshot update [skip ci]'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
        with:
          destination_container_repo: ${{inputs.image-name}}
          provider: dockerhub
          short_description: ${{env.REPOSITORY_DESCRIPTION}}
          readme_file: README.md