name: Release Drafter

on:
  workflow_call:

jobs:
  update_release_draft:
    name: 📜 Creating Notes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: none
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
