name: Test

on:
  workflow_call:
    inputs:
      NAME:
        description: Enter a name for the job
        type: string
        required: false
        default: Test

      RUNS_ON:
        description: use runs-on to define the type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest

      TIMEOUT_MINUTES:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      TEST_COMMAND:
        description: Enter the command to run the tests
        type: string
        required: true

    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  test:
    name: ${{ inputs.NAME }}
    runs-on: ${{ inputs.RUNS_ON }}
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      REPOSITORY_SLUG: ${{ github.event.repository.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.REPOSITORY_SLUG }}
          path: /tmp

      - name: Load Image
        run: docker load --input /tmp/${{ env.REPOSITORY_SLUG }}.tar

      - name: Run Tests
        run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_SLUG }}:latest ${{ inputs.TEST_COMMAND }}