name: Tester

on:
  workflow_call:
    inputs:
      name:
        description: Enter a name for the job
        type: string
        required: false
        default: 🧪 Run Tests

      runs-on:
        description: use runs-on to define the type of machine to run the job on
        type: string
        required: false
        default: ubuntu-latest

      timeout-minutes:
        description: Specifies the maximum execution time of the job (in minutes)
        type: number
        required: false
        default: 25

      command:
        description: Enter the command to be executed inside the container
        type: string
        required: true

      image-name:
        description: Enter the name of the image
        type: string
        required: false

      image-tag:
        description: Enter the label that will serve to identify the image in future works
        type: string
        required: false
        default: latest

jobs:
  loader:
    name: ${{inputs.name}}
    runs-on: ${{inputs.runs-on}}
    timeout-minutes: ${{inputs.timeout-minutes}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{inputs.image-tag}}
          path: /tmp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Image
        run: docker load --input /tmp/${{inputs.image-tag}}.tar

      - name: Run Command
        env:
          IMAGE: (${{inputs.image-name}} || ${{github.event.repository.owner.login}}/${{github.event.repository.name}})
        run: docker run ${{env.IMAGE}}:${{inputs.image-tag}} ${{inputs.command}}
